homeassistant:
  # Name of the location where Home Assistant is running
  name: WILLIAM LOTT MANOR
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: America/Toronto

  # Customization file
  customize: !include customize.yaml
# Enables configuration UI
config:
cloud:
  alexa:
    filter:
      include_entities:
#        - group.all_lights
        - group.all_switches
#        - group.interior_lights
#        - group.bedroom_lights
#        - group.living_room_lights
#        - group.living_room_accents
#        - group.dinette_lights
#        - group.dining_room_lights
#        - group.den_lights
#        - group.foyer_lights
#        - group.office_lights
#        - group.hallway_lights
#        - group.kitchen_lights
#        - group.upstairs_lights
#        - group.outdoor_pool_lights
#        - group.garage_lights
#        - group.paiges_room
#        - group.justins_room
#        - group.Exterior_Lights
#        - group.outdoor_pool_lights
#        - group.outdoor_front_lights
#        - group.landscaping
      include_domains:
        - switch
      #  - cover
      #  - input_boolean
      # exclude_entities:
      # exclude_domains:
      #   - light
      #   - media_player
#    entity_config:
#      group.kitchen_lights:
#        display_categories: LIGHT
#      group.bedroom_lights:
#        display_categories: LIGHT
#      group.upstairs_lights:
#        display_categories: LIGHT
http:
#  base_url: https://williamlottmanor.duckdns.org:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
    
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

# Enables the frontend
frontend:

homekit:
  auto_start: false
  
# Discover some devices automatically
discovery:
    

updater:
  include_used_components: true

# Track the sun
sun:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover
      - alarm_control_panel
#  exclude:
#    entities:
#     - sensor.last_boot
#     - sensor.date
#     - sensor.pihole_ads_blocked_today
#     - sensor.pihole_ads_percentage_blocked_today
#     - sensor.pihole_dns_queries_today
#     - sensor.since_last_boot
#     - sensor.since_last_boot_templated
#     - sensor.floorplan_date
#     - sensor.floorplan_time
#     - sensor.ha_uptime
#     - sensor.time

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10


# Enables a map showing the location of tracked devices
#map:

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: smartthings
#  keepalive: 60
#  client_id: hassio
#  username: !secret mqtt_username
#  password: !secret mqtt_pw
  
  

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain
    
# Text to speech
tts:
  - platform: google

ecobee:

apple_tv:

#ios:
  
tradfri:
  host: 192.168.1.18
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
alarm_control_panel: !include alarm.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
media_player: !include media_players.yaml

